name: PHP Tests

on: [push, pull_request, release]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php_version:
          - '8.2'
          - '8.1'
          - '8.0'
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3


    env:
      WP_VERSION: latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          extensions: |
            xdebug
            pdo
          coverage: pcov

      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          mv composer.phar /usr/local/bin/composer

      - name: Clear Xdebug configuration (if present)
        run: |
          if [ -f /etc/php/*/cli/conf.d/20-xdebug.ini ]; then
            echo "Removing Xdebug configuration"
            sudo rm /etc/php/*/cli/conf.d/20-xdebug.ini
          else
            echo "Xdebug configuration not found"
          fi

      - name: Cache Composer dependencies
        run: composer install

      - name: Setup PhpUnit
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_NAME: wordpress_test
          DB_USER: root
          DB_PASS: root
        run: bash bin/install-wp-tests.sh wordpress_test root root 127.0.0.1 $WP_VERSION

      - name: Run single site tests
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_NAME: wordpress_test
          DB_USER: root
          DB_PASS: root
        run: composer run test:coverage-text

      - name: Run multi-site tests
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_NAME: wordpress_test
          DB_USER: root
          DB_PASS: root
          WP_MULTISITE: true
        run: composer run test:coverage-text

      - name: Run PHP CodeSniffer
        run: |
          composer run phpcs

      # Install Node.js 12.x
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12.x

      # Build with Node.js (assuming you have the necessary build scripts)
      - name: Install Node.js dependencies and Build
        run: |
          npm install
          npm run build

      # Create the artifact zip
      - name: Create build artifact
        run: git archive -o anspress-question-answer.zip HEAD --prefix=anspress-question-answer/

      # Upload the artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: anspress-question-answer
          path: anspress-question-answer.zip
